### PR TITLE
Implement DataType for rgb types to allow working with colors easier

### PR DESCRIPTION
**Pull request by fzyzcjy**
P.S. Please only look at commits after Oct 28. All commits before that have been merged already, and I am not sure why GitHub still shows them.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
oops I forgot to mention @twistedfall 

p.s. For example, this pr allows me to treat`ARGB8` similar to Vec4b. Then, I can happily convert `Array2<ARGB8>` (array of dim 2, 4 channel, type u8, and in ARGB order instead of RGBA) to `Mat` without any trouble.

**Comment by twistedfall** [comment]
> I am not sure why GitHub still shows them.

You are using your branch as a base, but I squashed the commits when I was merging your Mat operations PR, that's why :) If you rebase your changes on the current `master` then it will show as expected.

> oops I forgot to mention @twistedfall

There is no need to mention me explicitly in general, I'm getting the notifications about all PRs :)

**Comment by fzyzcjy** [comment]
> There is no need to mention me explicitly in general, I'm getting the notifications about all PRs :)

Ah I did not know that. Thanks for pointing out

**Comment by fzyzcjy** [comment]
🎉

**Pull request merged**
