### PR TITLE
support opencv4 with OPENCV_FORCE_3RDPARTY_BUILD

### PR DESCRIPTION
**Pull request by flisky**
my first naive try on travis, rust and opencv :)

### CODE REVIEW

**Comment by twistedfall** [comment]
Hi, thank you for your contribution and effort! As far as I can see this branch is still under heavy development and there is still no success in building the crate with opencv-4.1. I'm going to close this pull request for now, please feel free to reopen it when things are in better shape. Yet, I still feel you're going in the wrong direction trying to build it without shared libs.

**Comment by flisky** [comment]
Thank you for the reply!

I'm trying to do some image processing with opencv.
And yes, I'm trying to build it without shared libs, and I'm also turning the `OPENCV_FORCE_3RDPARTY_BUILD=ON`. It's enough to go with `imgcodec` and `imgproc` modules for me:)

I rebase the PR and CI passes in local machine. Could you please take another look? In fact, only the 2nd commit is enough to me. I'm happy to drop the 3rd commit (`-DBUILD_SHARD_LIB=OFF -DOPENCV_FORCE_3RDPARTY_BUILD=ON`) if you don't like it.

**Comment by flisky** [comment]
It seems github won't auto-refresh commits for closed PR. Could you reopen?

**Comment by twistedfall** [comment]
Github doesn't allow me to reopen it either, on the grounds of "master branch was force-pushed or recreated". Can you please try doing the [following](https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c)?

**Comment by flisky** [comment]
Sorry, `reflog` too dirty. Reopen as #44.

**Pull request closed without merging**
