### PR TITLE
Support opencv-3.4.5

### PR DESCRIPTION
**Pull request by twistedfall**
Hi,

This PR enables building of the crate with opencv-3.4.5 and adds some modules not present in current master branch (e.g. ml). contrib modules are mostly not tested, some might work. I know it's quite huge, but the main things done are:
* rebase old cv3 branch on master
* merge changes to hdr_parser.py from upstream
* generated rust modules now reside under src so that IDE can pick them up
* changes in handling abstract classes/traits, allowed to generate most of the ml module
* some changes in function naming so no BC is guaranteed
* mutable references for OutputArray and InputOutputArray
* errors are now sent via a separate Error type and include error_code
* add a lot of additonal types to parsing and fix handling of already existing types, that led to more generated functions

### CODE REVIEW

**Comment by kali** [comment]
Wow. Thanks :)

Would you like to "adopt" the library ?

**Comment by twistedfall** [comment]
If you don't have time and/or desire to work on it anymore, then yes. I've gained enough knowledge of its internals to be able to support it.

**Comment by kali** [comment]
Good. That's exactly the situation.

**Comment by kali** [comment]
I need you to rename your fork so that I can transfer this repo to you :)

**Comment by twistedfall** [comment]
Done

**Comment by twistedfall** [comment]
Will you please do the same with crates.io?

**Comment by kali** [comment]
All right, according to this: https://help.github.com/en/articles/transferring-a-repository, renaming is not enough we will need you to delete the fork prior to the transfer.

So let's merge wait for this PR to be merged and then we can do the transfer. I assume you will want to try and get the CI fixed before we merge.

And yeah, I will also give you rights on crates.io, of course.

**Comment by twistedfall** [comment]
Well, the whole Travis CI thing is new to me and I don't really have time right now to get to the bottom of this, unfortunately. I suggest we do the merging first.

**Comment by kali** [comment]
All right, you're the boss :)

**Comment by kali** [comment]
So it's merged, you can archive your repo now, and I'll try the transfer again

**Comment by twistedfall** [comment]
Done

**Comment by kali** [comment]
ok, transfer request is successful this time, and you should have been invited as an owned to crates too.

**Comment by twistedfall** [comment]
Thank you, everything worked perfectly!

**Comment by kali** [comment]
Great, and enjoy :) I'll be around if you have question or if we missed something.

**Comment by dralley** [comment]
Wow this is awesome!  I'm glad that this library is getting some love once more.

**Pull request merged**
