### PR TITLE
opencv4 compatibility

### PR DESCRIPTION
**Pull request by flisky**
My second try on #43

### CODE REVIEW

**Comment by twistedfall** [comment]
Looks good, but yes, let's drop the 3rd commit with disabling shared libs. I feel it's too specific to your project and I'd like to keep CI environment as generic as possible.

**Comment by flisky** [comment]
Oh, some APIs have changed:(

For example, `cv_VideoCapture_VideoCapture_int` is removed, and `cv_decodeQRCode_Mat_VectorOfPoint_std_string_Mat` is replaced by [QRCodeDetector.detectAndDecode](https://docs.opencv.org/4.1.0/de/dc3/classcv_1_1QRCodeDetector.html#a7290bd6a5d59b14a37979c3a14fbf394).

Any solution to handle these cases?

**Comment by twistedfall** [comment]
Well, currently we don't support 2 sets of generated bindings. Do you know if those 2 functions are the only which are causing linking issues? If so we might as well drop them, they have replacements in 3.4 too. To drop the function from generation, please add the following to `func_rename` dictionary in `gen_rust.py`:

```python
"cv_VideoCapture_VideoCapture_int": "-",
"cv_decodeQRCode_Mat_VectorOfPoint_std_string_Mat": "-",
"cv_detectQRCode_Mat_VectorOfPoint_double_double": "-",
```

**Comment by twistedfall** [comment]
Hi, I've implemented the support for OpenCV-4.1.0, please check the Readme.md on how to use it, thanks for the PR, I've used most of it!

**Pull request merged**
