### PR TITLE
unit: a failing unit test to feature2d::BFMatcher

### PR DESCRIPTION
**Pull request by sjbeskur**
You don't really want to merge this yet but I could use some help figuring this out

### CODE REVIEW

**Comment by twistedfall** [comment]
Thanks! This is related to https://github.com/twistedfall/opencv-rust/issues/489, am I right? I'm away from the computer at the moment for a while, but I'll check it as soon as possible

**Comment by sjbeskur** [comment]
Yes that is correct this is related to issue #489.   No  rush and thanks for your attention.. Happy to help where I can be useful.

**Comment by sjbeskur** [comment]
anyone have and further insights on this?

**Comment by twistedfall** [comment]
Sorry for taking so long to get back to you! In this case the problem is that you must use the `train_match` function instead of `match_` like this:
```rust
	let mut matches = opencv::types::VectorOfDMatch::new();
	bf_matcher.train_match(&des_a, &des_b, &mut matches, &no_array()).unwrap();
```

**Comment by sjbeskur** [comment]
Brilliant..  yep that did the trick.  I've updated my pull request but maybe it's better as an example in case someone else has the same issue.

**Pull request merged**
